Add Introduction Page
LibertyDSNP/frequency-docs pull request #32
Opened 2022-10-12 14:24 UTC by ebroady

Added Introduction Page

2022-10-12 14:27 UTC, wilwade requested changes
Spell check and I suggest one sentence per line.

2022-10-18 13:56 UTC, wilwade commented on pages/index.md
> +It provides scalable message passion as a backbone of new shared protocols that create value through cooperation and user choice.
We might want to re-write the intro based on the content on https://www.frequency.xyz/

```suggestion
It provides scalable message passing as a backbone of new shared protocols that create value through cooperation and user choice. 
```

2022-10-18 13:56 UTC, wilwade commented on pages/index.md
> +	* Smart Schemas
Trying out a different word over "smart". Thoughts?
```suggestion
	* Shared Schemas
```

2022-10-18 13:56 UTC, wilwade commented on pages/index.md
> +## Lack of Financial Incentive for dApps:
Not sure about this suggestion, but I think we need to re-write this section. Let's talk about it.

```suggestion
## Financial Incentive Freedom for Applications on DSNP and Frequency: 
```

2022-10-18 13:56 UTC, wilwade commented on Initial Distribution.md
> +##Initial Token Distribution:
These extra files from the other branch sneaked in.

2022-10-18 13:56 UTC, wilwade commented on .yaspellerrc.json
> +    "for dApps",
I would think this should work instead, but not sure we want to use the term dApps.
```suggestion
    "dApps",
```

2022-10-18 20:01 UTC, ebroady commented on pages/index.md
> +It provides scalable message passion as a backbone of new shared protocols that create value through cooperation and user choice.
Do we want to rewrite to go more into the "why" behind DSNP and Frequency or more to echo the writing style and content from this?

2022-10-18 20:23 UTC, wilwade commented on pages/index.md
> +It provides scalable message passion as a backbone of new shared protocols that create value through cooperation and user choice.
@ebroady I think we can add some. Let's keep to the writing style of the docs, so less "marketing" tone, and align it with the sections of the docs.

2022-10-18 21:41 UTC, ebroady commented on pages/index.md
> +## Scalability:
Could see this being moved to a different page for additional information to be contributed. Could overlap with the future roadmap content.

2022-10-18 21:43 UTC, ebroady commented on pages/index.md
> +## Financial Incentive Freedom for Applications on DSNP and Frequency:
Same as Scalability - Depends on how much content we want to have on the introduction page - I feel like this could be broken up into smaller pieces.

2022-10-18 21:44 UTC, ebroady commented on pages/index.md
> +## Scalability:
Perhaps under Learn -> Vision section

2022-10-18 21:57 UTC, ebroady commented on pages/index.md
> +	* Capacity
Can't link to Capacity page until it is committed to Summary page on the Intro branch

2022-10-19 12:56 UTC, wilwade reviewed
Few small notes.

2022-10-19 12:56 UTC, wilwade commented on pages/index.md
> +Frequency is the first implementation of [The Decentralized Social Network Protocol (DSNP)](https://www.dsnp.org/introducing-dsnp.html) operating as a Polkadot parachain.
```suggestion
Frequency is the first implementation of [The Decentralized Social Network Protocol (DSNP)](https://www.dsnp.org/) operating as a Polkadot parachain. 
```

2022-10-19 12:56 UTC, wilwade commented on pages/index.md
> +The project originated with [Unfinished](https://www.unfinishedlabs.io/), a social impact organization with a network of partners engaged in technology, academia, social impact, and the arts. The fir
```suggestion
The project originated with [Unfinished](https://www.unfinished.com/), a social impact organization with a network of partners engaged in technology, academia, social impact, and the arts. The first phase of work focused on delivering the social network as core internet functionality.  The Decentralized Social Network, DSNP serves as a public resource entirely independent of financial incentives. Frequency is the second strange of work and unlocks decentralized social networking at scale for the first time.
```

2022-10-19 12:56 UTC, wilwade commented on pages/index.md
> +To learn more about decentralized social networks visit [DSNP.org](https://www.dsnp.org/introducing-dsnp.html)
```suggestion
To learn more about decentralized social networks visit [DSNP.org](https://www.dsnp.org/)
```

2022-10-19 12:56 UTC, wilwade commented on pages/index.md
> +Building Frequency as a [Polkadot](https://wiki.polkadot.network/docs/getting-started) parachain offers a solution to the challenge of scaling a social networking platform.
```suggestion
Building Frequency as a [Polkadot](https://wiki.polkadot.network/) parachain offers a solution to the challenge of scaling a social networking platform. 
```

2022-10-19 12:56 UTC, wilwade commented on Initial Distribution.md
> +
I don't think we want this file.

2022-10-19 12:56 UTC, wilwade commented on pages/index.md
> +Implementation elements for this concept are currently under development.
Not sure how to word this section. Perhaps just coming soon and then we write the summary after we have the other content.
```suggestion
Coming soon
```

2022-10-19 19:16 UTC, wilwade approved these changes
Merge it!

2022-10-19 19:17 UTC, merged